# Generated by Django 6.0.4 on 2026-04-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField()),
                ('features', models.JSONField()),
                ('api_endpoints', models.JSONField(default=list)),
                ('github_link', models.URLField()),
                ('live_link', models.URLField(blank=True)),
                ('status', models.CharField(default='Live', max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qa_testing_type', models.CharField(blank=True, max_length=100)),
                ('qa_description', models.TextField(blank=True)),
                ('qa_tags', models.JSONField(default=list)),
                ('qa_total', models.IntegerField(default=0)),
                ('qa_passed', models.IntegerField(default=0)),
                ('qa_failed', models.IntegerField(default=0)),
                ('qa_sheet_link', models.URLField(blank=True)),
            ],
        ),
    ]
