# Generated by Django 6.0.4 on 2026-04-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_academiccertification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccertification',
            name='certificate',
            field=models.ImageField(blank=True, upload_to='academic_certificates/'),
        ),
    ]
