# Generated by Django 6.0.4 on 2026-04-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_academiccertification_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='api_endpoints',
        ),
        migrations.AlterField(
            model_name='project',
            name='qa_failed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='qa_passed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='qa_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='qa_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
