# Generated by Django 6.0.4 on 2026-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_project_api_endpoints_alter_project_qa_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='api_docs_link',
            field=models.URLField(blank=True),
        ),
    ]
