# Generated by Django 5.2.1 on 2025-06-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('Dj', 'Django'), ('Py', 'Python'), ('Fg', 'Figma')], max_length=2)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list)),
                ('vedio', models.FileField(upload_to='')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
