# Generated by Django 5.2.1 on 2025-06-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vedio',
            field=models.FileField(upload_to='static/videos/'),
        ),
    ]
