# Generated by Django 5.2.1 on 2025-06-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vedio',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/'),
        ),
    ]
