# Generated by Django 5.2.1 on 2025-06-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_project_vedio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('AC', 'Academic'), ('CE', 'Certification')], max_length=2)),
                ('institute', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
