# Generated by Django 6.0.1 on 2026-01-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_qualification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
