# Generated by Django 5.1.1 on 2026-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_alter_project_options_project_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='figma_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
