# Generated by Django 6.0.1 on 2026-01-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_project_figma_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brief_overview',
            field=models.CharField(default='breif_overview', help_text='A 2-sentence summary for the Hero section.', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(default='problem_statement', help_text='What was the challenge?'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_statement',
            field=models.TextField(default='solution_statement', help_text='How did you solve it?'),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_breakdown',
            field=models.TextField(default='technical_breakdown', help_text='The deep dive/README content.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Used for the project card preview.'),
        ),
    ]
