# Generated by Django 6.0.1 on 2026-01-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_project_brief_overview_project_problem_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, default='problem_statement', help_text='What was the challenge?', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution_statement',
            field=models.TextField(blank=True, default='solution_statement', help_text='How did you solve it?', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technical_breakdown',
            field=models.TextField(blank=True, default='technical_breakdown', help_text='The deep dive/README content.', null=True),
        ),
    ]
