# Generated by Django 6.0.1 on 2026-01-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_alter_project_problem_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Live', 'Live & Production'), ('Beta', 'In Beta Testing'), ('Dev', 'In Development'), ('Arch', 'Archived/Concept')], default='Dev', max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Dj', 'Django'), ('Py', 'Python'), ('Fg', 'Figma'), ('FS', 'Full Stack')], max_length=2),
        ),
    ]
