# Generated by Django 6.0.1 on 2026-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_project_status_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Comp', 'Completed'), ('Live', 'Live & Production'), ('Dev', 'In Development')], default='Dev', max_length=4),
        ),
    ]
