# Generated by Django 6.0.1 on 2026-01-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='brief_overview',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Comp', 'Completed'), ('Live', 'Live'), ('Dev', 'In Development')], default='Dev', max_length=4),
        ),
    ]
